import { MigrationInterface, QueryRunner } from "typeorm";

export class VerificationSchemaDriftFix1788338212245 implements MigrationInterface {
    name = 'VerificationSchemaDriftFix1788338212245'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_posts_quotedPost"`);
        await queryRunner.query(`ALTER TABLE "podcasts" DROP CONSTRAINT "FK_podcasts_authorId"`);
        await queryRunner.query(`ALTER TABLE "newsletters" DROP CONSTRAINT "FK_newsletters_authorId"`);
        await queryRunner.query(`ALTER TABLE "newsletter_subscribers" DROP CONSTRAINT "FK_newsletter_subscribers_userId"`);
        await queryRunner.query(`ALTER TABLE "newsletter_newslettersubscribers" DROP CONSTRAINT "FK_nns_authorId"`);
        await queryRunner.query(`ALTER TABLE "newsletter_newslettersubscribers" DROP CONSTRAINT "FK_nns_subscriberId"`);
        await queryRunner.query(`ALTER TABLE "signed_prekeys" DROP CONSTRAINT "FK_spk_userId"`);
        await queryRunner.query(`ALTER TABLE "prekey_bundles" DROP CONSTRAINT "FK_pkb_userId"`);
        await queryRunner.query(`ALTER TABLE "one_time_prekeys" DROP CONSTRAINT "FK_otpk_userId"`);
        await queryRunner.query(`ALTER TABLE "invite_codes" DROP CONSTRAINT "FK_invite_codes_created_by"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_courses_authorId"`);
        await queryRunner.query(`ALTER TABLE "course_lessons" DROP CONSTRAINT "FK_course_lessons_courseId"`);
        await queryRunner.query(`ALTER TABLE "course_enrollments" DROP CONSTRAINT "FK_course_enrollments_courseId"`);
        await queryRunner.query(`ALTER TABLE "course_enrollments" DROP CONSTRAINT "FK_course_enrollments_userId"`);
        await queryRunner.query(`ALTER TABLE "articles" DROP CONSTRAINT "FK_articles_authorId"`);
        await queryRunner.query(`ALTER TABLE "webhook_endpoints" DROP CONSTRAINT "FK_webhook_endpoints_developer"`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" DROP CONSTRAINT "FK_ledger_entries_userId"`);
        await queryRunner.query(`ALTER TABLE "webhook_deliveries" DROP CONSTRAINT "FK_webhook_deliveries_endpoint"`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" DROP CONSTRAINT "FK_verification_appeals_user"`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" DROP CONSTRAINT "FK_verification_appeals_request"`);
        await queryRunner.query(`ALTER TABLE "thread_messages" DROP CONSTRAINT "FK_thread_messages_thread_id"`);
        await queryRunner.query(`ALTER TABLE "thread_messages" DROP CONSTRAINT "FK_thread_messages_user_id"`);
        await queryRunner.query(`ALTER TABLE "thread_messages" DROP CONSTRAINT "FK_thread_messages_parent_message_id"`);
        await queryRunner.query(`ALTER TABLE "threads" DROP CONSTRAINT "FK_threads_user_id"`);
        await queryRunner.query(`ALTER TABLE "tax_documents" DROP CONSTRAINT "FK_tax_documents_user"`);
        await queryRunner.query(`ALTER TABLE "subscription_bundles" DROP CONSTRAINT "FK_subscription_bundles_creator"`);
        await queryRunner.query(`ALTER TABLE "subscription_bundle_tiers" DROP CONSTRAINT "FK_bundle_tiers_bundle"`);
        await queryRunner.query(`ALTER TABLE "subscription_bundle_tiers" DROP CONSTRAINT "FK_bundle_tiers_tier"`);
        await queryRunner.query(`ALTER TABLE "security_audit_logs" DROP CONSTRAINT "FK_security_audit_logs_user"`);
        await queryRunner.query(`ALTER TABLE "scheduled_posts" DROP CONSTRAINT "FK_scheduled_posts_user_id"`);
        await queryRunner.query(`ALTER TABLE "oauth_apps" DROP CONSTRAINT "FK_oauth_apps_developer"`);
        await queryRunner.query(`ALTER TABLE "oauth_authorizations" DROP CONSTRAINT "FK_oauth_auth_app"`);
        await queryRunner.query(`ALTER TABLE "oauth_authorizations" DROP CONSTRAINT "FK_oauth_auth_user"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP CONSTRAINT "FK_product_reviews_productId"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP CONSTRAINT "FK_product_reviews_reviewerId"`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" DROP CONSTRAINT "FK_escrow_buyerId"`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" DROP CONSTRAINT "FK_escrow_sellerId"`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" DROP CONSTRAINT "FK_escrow_productId"`);
        await queryRunner.query(`ALTER TABLE "checkout_sessions" DROP CONSTRAINT "FK_checkout_buyerId"`);
        await queryRunner.query(`ALTER TABLE "checkout_sessions" DROP CONSTRAINT "FK_checkout_productId"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_invoices_user"`);
        await queryRunner.query(`ALTER TABLE "group_lockdowns" DROP CONSTRAINT "FK_group_lockdowns_group"`);
        await queryRunner.query(`ALTER TABLE "group_lockdowns" DROP CONSTRAINT "FK_group_lockdowns_creator"`);
        await queryRunner.query(`ALTER TABLE "federation_moderations" DROP CONSTRAINT "FK_federation_moderations_local_user"`);
        await queryRunner.query(`ALTER TABLE "federation_moderations" DROP CONSTRAINT "FK_federation_moderations_remote_user"`);
        await queryRunner.query(`ALTER TABLE "brainwave_devices" DROP CONSTRAINT "FK_brainwave_devices_userId"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP CONSTRAINT "FK_5aeaa2dd850bc2ca311c793716d"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP CONSTRAINT "FK_f8f7551b0df6a9d20a328125305"`);
        await queryRunner.query(`ALTER TABLE "security_alerts" DROP CONSTRAINT "FK_security_alerts_user"`);
        await queryRunner.query(`ALTER TABLE "user_mutes" DROP CONSTRAINT "FK_user_mutes_user"`);
        await queryRunner.query(`ALTER TABLE "user_mutes" DROP CONSTRAINT "FK_user_mutes_muted_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_podcasts_slug"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_podcasts_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_spk_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pkb_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_otpk_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_otpk_userId_unused"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invite_codes_code"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_courses_slug"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_articles_slug"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_articles_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_articles_authorId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_articles_publishedAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ledger_entries_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_webhook_deliveries_endpoint"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_verification_appeals_request_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_verification_appeals_user_submitted"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tip_recipient_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_thread_messages_thread_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_thread_messages_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_threads_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_tax_document_user_year_form"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_scheduled_posts_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_scheduled_posts_status_due"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_oauth_auth_codeHash"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_oauth_auth_app"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_product_reviews_productId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_federation_moderations_local_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_federation_moderations_remote_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_custom_audiences_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_connected_accounts_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_brainwave_devices_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_doc_records_accountId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_doc_records_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_doc_records_documentId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_doc_records_submittedAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_doc_records_accountId_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_rules_enabled"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_logs_accountId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_logs_action"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_logs_createdAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_appeals_documentRecordId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_appeals_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_appeals_createdAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_stats_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_security_alerts_user_status_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_mutes_muted_user"`);
        await queryRunner.query(`ALTER TABLE "federation_moderations" DROP CONSTRAINT "UQ_federation_moderations_pair"`);
        await queryRunner.query(`CREATE TABLE "biometric_devices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "deviceId" character varying NOT NULL, "deviceName" character varying NOT NULL DEFAULT 'Biometric Device', "biometricType" character varying NOT NULL DEFAULT 'face', "fingerprint" character varying(512) NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "lastUsedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e959efdfa762cf108f76611f5e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."verification_history_eventtype_enum" AS ENUM('request_submitted', 'under_review', 'approved', 'rejected', 'badge_granted', 'badge_revoked', 'appeal_submitted', 'appeal_approved', 'appeal_rejected', 'document_verified', 'document_rejected')`);
        await queryRunner.query(`CREATE TABLE "verification_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "eventType" "public"."verification_history_eventtype_enum" NOT NULL, "description" text, "metadata" text, "performedBy" uuid, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9d7b75d42e1bd803aee0f90c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_94429d4ee17e28bf15bd918ef7" ON "verification_history" ("eventType", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_519bc2d63c2d3a5f9fe4f4a19b" ON "verification_history" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."verification_badges_type_enum" AS ENUM('creator', 'business', 'organization', 'verified_identity', 'verified_age', 'official', 'trusted')`);
        await queryRunner.query(`CREATE TABLE "verification_badges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "type" "public"."verification_badges_type_enum" NOT NULL, "displayName" text, "description" text, "iconUrl" character varying, "isActive" boolean NOT NULL DEFAULT true, "grantedAt" TIMESTAMP NOT NULL DEFAULT now(), "expiresAt" TIMESTAMP, "grantedBy" uuid, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "revocationReason" text, "revokedAt" TIMESTAMP, CONSTRAINT "PK_967cad3677b71ddea1a57de5ad2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3f17990a187f550345129925d5" ON "verification_badges" ("userId", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."trust_indicators_trustlevel_enum" AS ENUM('unknown', 'low', 'medium', 'high', 'verified')`);
        await queryRunner.query(`CREATE TABLE "trust_indicators" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "trustLevel" "public"."trust_indicators_trustlevel_enum" NOT NULL DEFAULT 'unknown', "trustScore" integer NOT NULL DEFAULT '0', "verificationCount" integer NOT NULL DEFAULT '0', "badgeCount" integer NOT NULL DEFAULT '0', "isVerified" boolean NOT NULL DEFAULT false, "hasCompletedIdentityVerification" boolean NOT NULL DEFAULT false, "hasCompletedAgeVerification" boolean NOT NULL DEFAULT false, "accountAgeInDays" integer NOT NULL DEFAULT '0', "postCount" integer NOT NULL DEFAULT '0', "followerCount" integer NOT NULL DEFAULT '0', "hasProfilePhoto" boolean NOT NULL DEFAULT false, "hasCompletedProfile" boolean NOT NULL DEFAULT false, "reportCount" integer NOT NULL DEFAULT '0', "isBanned" boolean NOT NULL DEFAULT false, "badges" text, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2553489e8fab128aa538d8b088c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d1dd47df7dbad1fff04a54bf86" ON "trust_indicators" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."login_approvals_status_enum" AS ENUM('pending', 'approved', 'rejected', 'expired')`);
        await queryRunner.query(`CREATE TABLE "login_approvals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "deviceName" character varying NOT NULL, "ipAddress" character varying, "userAgent" text, "location" character varying, "browser" character varying, "os" character varying, "status" "public"."login_approvals_status_enum" NOT NULL DEFAULT 'pending', "approvalToken" character varying, "tokenExpiresAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "approvedAt" TIMESTAMP, "reviewedAt" TIMESTAMP, "reviewedBy" uuid, "reviewerNote" text, "rememberDevice" boolean NOT NULL DEFAULT false, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7c7912932dd2fde8e8580bd5547" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4a5d8198376a76b0d668dcf423" ON "login_approvals" ("status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_454cadf17c215212f16993cd55" ON "login_approvals" ("userId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."linked_accounts_provider_enum" AS ENUM('google', 'facebook', 'twitter', 'github', 'apple', 'discord')`);
        await queryRunner.query(`CREATE TABLE "linked_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "provider" "public"."linked_accounts_provider_enum" NOT NULL, "externalUserId" character varying NOT NULL, "displayName" character varying, "email" character varying, "profilePictureUrl" character varying, "isPrimary" boolean NOT NULL DEFAULT false, "isVerified" boolean NOT NULL DEFAULT false, "metadata" text, "connectedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "lastUsedAt" TIMESTAMP, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_445bf7a50aeeb7f0084052935a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_85a88f8035617f15d7d5749104" ON "linked_accounts" ("provider", "externalUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ba6eb6c390ea493cd072735ed" ON "linked_accounts" ("userId", "provider") `);
        await queryRunner.query(`CREATE TABLE "identity_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "legalName" character varying(255), "displayName" character varying(255), "bio" text, "publicProfile" boolean NOT NULL DEFAULT false, "creatorMode" boolean NOT NULL DEFAULT false, "businessMode" boolean NOT NULL DEFAULT false, "businessName" character varying, "businessRegistrationNumber" character varying, "businessAddress" text, "ageVerified" boolean NOT NULL DEFAULT false, "verifiedBirthDate" date, "ageVerificationDate" TIMESTAMP, "enhancedSecurity" boolean NOT NULL DEFAULT false, "verificationRequired" boolean NOT NULL DEFAULT false, "organizationName" character varying, "organizationRegistrationNumber" character varying, "organizationWebsite" text, "customFields" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_940bf86f55bf16a68a4998e1dcf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_065a1847df05510051ec6d8194" ON "identity_settings" ("userId") `);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "registrationId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "deviceId"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "reviewNote"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "reviewedById"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "justification"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "links"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "category"`);
        await queryRunner.query(`DROP TYPE "public"."verification_requests_category_enum"`);
        await queryRunner.query(`ALTER TABLE "token_gated_content" ADD "chainId" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "token_gated_content" ADD "tier" character varying NOT NULL DEFAULT 'basic'`);
        await queryRunner.query(`ALTER TABLE "nonprofits" ADD "rejectionReason" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isGuest" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`CREATE TYPE "public"."verification_requests_workflow_enum" AS ENUM('personal', 'business', 'organization')`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "workflow" "public"."verification_requests_workflow_enum" NOT NULL DEFAULT 'personal'`);
        await queryRunner.query(`CREATE TYPE "public"."verification_requests_category_enum" AS ENUM('creator', 'business', 'journalist', 'government', 'nonprofit', 'other')`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "category" "public"."verification_requests_category_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "organizationName" character varying`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "documentType" character varying`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "justification" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "links" jsonb NOT NULL DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "reviewNote" text`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "reviewedById" uuid`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" ADD "slug" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" ADD CONSTRAINT "UQ_9f8e1468d806ae7d98169bc78a3" UNIQUE ("slug")`);
        await queryRunner.query(`CREATE TYPE "public"."dao_proposal_type_enum" AS ENUM('community', 'treasury', 'governance')`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" ADD "type" "public"."dao_proposal_type_enum" NOT NULL DEFAULT 'community'`);
        await queryRunner.query(`CREATE TYPE "public"."dao_proposal_status_enum" AS ENUM('active', 'passed', 'rejected', 'executed', 'expired')`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" ADD "status" "public"."dao_proposal_status_enum" NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" ADD "quorum" integer NOT NULL DEFAULT '10'`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" ADD "passThreshold" numeric(5,2) NOT NULL DEFAULT '50'`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" ADD "votingEndsAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" ADD "treasuryAmount" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" ADD "yesVotes" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" ADD "noVotes" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" ADD "abstainVotes" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" ADD "totalVotes" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."verification_requests_type_enum" AS ENUM('creator', 'business', 'organization', 'identity', 'age')`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "type" "public"."verification_requests_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "metadata" text`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "documentUrl" text`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "rejectionReason" text`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "reviewedBy" uuid`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "submittedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "reviewedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "appealCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "nextAppealEligibleAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" ADD "metadata" text`);
        await queryRunner.query(`ALTER TABLE "podcasts" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."podcasts_status_enum" AS ENUM('draft', 'published', 'archived')`);
        await queryRunner.query(`ALTER TABLE "podcasts" ADD "status" "public"."podcasts_status_enum" NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "podcasts" DROP COLUMN "tags"`);
        await queryRunner.query(`ALTER TABLE "podcasts" ADD "tags" text`);
        await queryRunner.query(`ALTER TABLE "podcasts" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "podcasts" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "podcasts" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "podcasts" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "newsletters" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."newsletters_status_enum" AS ENUM('draft', 'scheduled', 'sent')`);
        await queryRunner.query(`ALTER TABLE "newsletters" ADD "status" "public"."newsletters_status_enum" NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "newsletters" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "newsletters" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "newsletters" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "newsletters" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "newsletter_subscribers" DROP COLUMN "subscribedAt"`);
        await queryRunner.query(`ALTER TABLE "newsletter_subscribers" ADD "subscribedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "newsletter_newslettersubscribers" DROP COLUMN "subscribedAt"`);
        await queryRunner.query(`ALTER TABLE "newsletter_newslettersubscribers" ADD "subscribedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "signed_prekeys" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "signed_prekeys" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "prekey_bundles" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "prekey_bundles" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "one_time_prekeys" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "one_time_prekeys" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."courses_status_enum" AS ENUM('draft', 'published', 'archived')`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "status" "public"."courses_status_enum" NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "course_lessons" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "course_lessons" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "course_lessons" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "course_lessons" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "course_enrollments" DROP COLUMN "completedLessons"`);
        await queryRunner.query(`ALTER TABLE "course_enrollments" ADD "completedLessons" text`);
        await queryRunner.query(`ALTER TABLE "course_enrollments" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "course_enrollments" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "articles" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."articles_status_enum" AS ENUM('draft', 'scheduled', 'published', 'archived')`);
        await queryRunner.query(`ALTER TABLE "articles" ADD "status" "public"."articles_status_enum" NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "articles" DROP COLUMN "tags"`);
        await queryRunner.query(`ALTER TABLE "articles" ADD "tags" text`);
        await queryRunner.query(`ALTER TABLE "articles" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "articles" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "articles" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "articles" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."verification_requests_status_enum" RENAME TO "verification_requests_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."verification_requests_status_enum" AS ENUM('pending', 'under_review', 'approved', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ALTER COLUMN "status" TYPE "public"."verification_requests_status_enum" USING "status"::"text"::"public"."verification_requests_status_enum"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."verification_requests_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "thread_messages" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "thread_messages" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "threads" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "threads" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "threads" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "threads" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "scheduled_posts" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "scheduled_posts" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD "title" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP COLUMN "images"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD "images" text`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."escrow_transactions_status_enum" AS ENUM('held', 'released', 'refunded', 'disputed')`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" ADD "status" "public"."escrow_transactions_status_enum" NOT NULL DEFAULT 'held'`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "checkout_sessions" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."checkout_sessions_status_enum" AS ENUM('pending', 'completed', 'failed', 'expired', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "checkout_sessions" ADD "status" "public"."checkout_sessions_status_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "checkout_sessions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "checkout_sessions" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "checkout_sessions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "checkout_sessions" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "instance_keys" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "instance_keys" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "instance_keys" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "instance_keys" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" ADD "description" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "brainwave_devices" ALTER COLUMN "userId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ALTER COLUMN "userId" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."verification_requests_status_enum" RENAME TO "verification_requests_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."verification_requests_status_enum" AS ENUM('pending', 'under_review', 'approved', 'rejected', 'appeal_pending')`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ALTER COLUMN "status" TYPE "public"."verification_requests_status_enum" USING "status"::"text"::"public"."verification_requests_status_enum"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."verification_requests_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" ADD "requestId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" DROP COLUMN "documentUrls"`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" ADD "documentUrls" text`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" DROP COLUMN "links"`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" ADD "links" text`);
        await queryRunner.query(`ALTER TABLE "document_verification_records" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "document_verification_records" ALTER COLUMN "submittedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "document_verification_records" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "document_verification_records" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "document_validation_rules" ALTER COLUMN "severity" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "document_validation_rules" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "document_validation_rules" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "document_verification_audit_logs" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "document_verification_appeals" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "document_verification_appeals" ALTER COLUMN "submittedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "document_verification_appeals" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "document_verification_stats" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_1123ff6815c5b8fec0ba9fec37" ON "articles" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_6c70d1c965d029dcd2af34025d" ON "ledger_entries" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9f63fc91ff6cbd3f8238b9a781" ON "webhook_deliveries" ("endpointId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d1ec1d0077a9029a4e4d3da930" ON "verification_appeals" ("userId", "submittedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_94005563c4ba7cabe1e59b937d" ON "verification_appeals" ("requestId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_1f2a4e59d61f895125d25bd3bc" ON "oauth_authorizations" ("appId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ab52c6673c6c1f6d54b63e60a6" ON "oauth_authorizations" ("codeHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_420b12a7a37822e748276ae4a8" ON "federation_moderations" ("localUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8d5c3c957770e934d6d09eb619" ON "federation_moderations" ("remoteUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3358e0885c861821636fdaa25c" ON "custom_audiences" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f60af098356f98fe6cfa060e3d" ON "connected_accounts" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f4007f95dc9b4b7d9c6aa5c813" ON "verification_requests" ("status", "submittedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_d66463591cafc24369366a0122" ON "verification_requests" ("userId", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_a8e61e380f80a7426c17563d0a" ON "verification_appeals" ("status", "submittedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_f198f0b1b0f69f186634733df0" ON "verification_appeals" ("userId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_f1ab3a29295d5c2507d606a1fb" ON "document_verification_records" ("accountId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_5c3081b6c7215589e8a4e00335" ON "document_verification_records" ("submittedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_b227208d15421af07c85d5abfd" ON "document_verification_records" ("documentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0187f2cd124ed7c9c4ff579744" ON "document_verification_records" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_4bd2925abbcfa498a9bfcbc3af" ON "document_verification_records" ("accountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b41c0c7dfa44b7228345042b93" ON "document_validation_rules" ("enabled") `);
        await queryRunner.query(`CREATE INDEX "IDX_503562c3b6df8516ae43a2f052" ON "document_verification_audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_0098a8274e33105c09719f8c5b" ON "document_verification_audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_00c876f1efd81fe6c660ac20fd" ON "document_verification_audit_logs" ("accountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f99d7fc3faae6108e514e8f00f" ON "document_verification_appeals" ("submittedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c54d74cdd7d268d6d6940d79a6" ON "document_verification_appeals" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d7629c18e0f5c46814bfe1ef9d" ON "document_verification_appeals" ("documentRecordId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce84151068834d5bfd63476156" ON "document_verification_stats" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_37d14e3c45fb3cb5791a329468" ON "security_alerts" ("userId", "resolved", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_cbedf76ebb0511716da7a6e9b1" ON "user_mutes" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_06f5a843540d98f44e7abbb47a" ON "user_mutes" ("mutedUserId") `);
        await queryRunner.query(`ALTER TABLE "tax_documents" ADD CONSTRAINT "UQ_tax_document_user_year_form" UNIQUE ("userId", "taxYear", "formType")`);
        await queryRunner.query(`ALTER TABLE "federation_moderations" ADD CONSTRAINT "UQ_db6a1ff672d21a5fe28f058693b" UNIQUE ("localUserId", "remoteUserId")`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_dda1f23593417fecd7a0d65033e" FOREIGN KEY ("quotedPostId") REFERENCES "posts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "podcasts" ADD CONSTRAINT "FK_7512a5861f9118a14e1d1bc9cd2" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "newsletters" ADD CONSTRAINT "FK_35109ef4f622c1c4619bd30fc4c" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "newsletter_subscribers" ADD CONSTRAINT "FK_52d6367f00d79849e585cf1e583" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "newsletter_newslettersubscribers" ADD CONSTRAINT "FK_c1ee4bbf7d7e34afd9ade85f3f9" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "newsletter_newslettersubscribers" ADD CONSTRAINT "FK_9627377ca0a655d80675ed0b467" FOREIGN KEY ("subscriberId") REFERENCES "newsletter_subscribers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signed_prekeys" ADD CONSTRAINT "FK_a0673f4690e84acb219961c1f29" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prekey_bundles" ADD CONSTRAINT "FK_a65ce317a25ffadf33195a345df" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "one_time_prekeys" ADD CONSTRAINT "FK_d8ca4e460ce7e0199de5d2280cc" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invite_codes" ADD CONSTRAINT "FK_7b103c31f0945f90b2af8d8ba0b" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_fffcbc92f4e8fa650d08be6903d" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_lessons" ADD CONSTRAINT "FK_a4dc7855b148a230609fbf38542" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_enrollments" ADD CONSTRAINT "FK_d77e489db35c7d325700d799be6" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_enrollments" ADD CONSTRAINT "FK_ab72c7fa06784137e905f1f8b8e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "articles" ADD CONSTRAINT "FK_65d9ccc1b02f4d904e90bd76a34" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webhook_endpoints" ADD CONSTRAINT "FK_ad15290f0cf98302ad7d68eae1c" FOREIGN KEY ("developerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD CONSTRAINT "FK_5aeaa2dd850bc2ca311c793716d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD CONSTRAINT "FK_f8f7551b0df6a9d20a328125305" FOREIGN KEY ("reviewedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" ADD CONSTRAINT "FK_6c70d1c965d029dcd2af34025db" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webhook_deliveries" ADD CONSTRAINT "FK_9f63fc91ff6cbd3f8238b9a7812" FOREIGN KEY ("endpointId") REFERENCES "webhook_endpoints"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" ADD CONSTRAINT "FK_8bd665642c690d77c06ef44c2fc" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" ADD CONSTRAINT "FK_c441120e2325a477c968c5caab2" FOREIGN KEY ("requestId") REFERENCES "verification_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "thread_messages" ADD CONSTRAINT "FK_c6bc073e77f201aa2fdbaa1688e" FOREIGN KEY ("thread_id") REFERENCES "threads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "thread_messages" ADD CONSTRAINT "FK_8a4e138370619824c68b6e9a419" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "thread_messages" ADD CONSTRAINT "FK_a82b034de86ec3aa77236c06cf8" FOREIGN KEY ("parent_message_id") REFERENCES "thread_messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "threads" ADD CONSTRAINT "FK_a6cc1a07ec07e376947ed1016a0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_documents" ADD CONSTRAINT "FK_d8ff960bc60b938ef2a27cc3407" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_bundles" ADD CONSTRAINT "FK_5186f53d7ad15cb9205d75a045e" FOREIGN KEY ("creatorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_bundle_tiers" ADD CONSTRAINT "FK_5321aaecbd03592a0473f1e7eba" FOREIGN KEY ("bundleId") REFERENCES "subscription_bundles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_bundle_tiers" ADD CONSTRAINT "FK_abe75c2db50cdd3085b4b8a055b" FOREIGN KEY ("tierId") REFERENCES "subscription_tiers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "security_audit_logs" ADD CONSTRAINT "FK_d7f3413ad98f1a72ef76e84bfec" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduled_posts" ADD CONSTRAINT "FK_83cbdfc52c73171cdff3b55e090" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_apps" ADD CONSTRAINT "FK_e7b22a2aeff109168c16a89af28" FOREIGN KEY ("developerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_authorizations" ADD CONSTRAINT "FK_1f2a4e59d61f895125d25bd3bc0" FOREIGN KEY ("appId") REFERENCES "oauth_apps"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_authorizations" ADD CONSTRAINT "FK_5baf2013e4d6649133b7ef56e38" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD CONSTRAINT "FK_32edd80d91dff1bc19e79c8f16d" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD CONSTRAINT "FK_842bd48e94f1d75a88221cfe35a" FOREIGN KEY ("reviewerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" ADD CONSTRAINT "FK_17d30a05cc8f0ea38b111f87e42" FOREIGN KEY ("buyerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" ADD CONSTRAINT "FK_98f900b8c9f8964a2639b24636b" FOREIGN KEY ("sellerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" ADD CONSTRAINT "FK_821f590b8289b844d4c5790242d" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "checkout_sessions" ADD CONSTRAINT "FK_4f7d6d4e50548afac8d8abc4b47" FOREIGN KEY ("buyerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "checkout_sessions" ADD CONSTRAINT "FK_6cd3a3b2162be33e3bd209a61a9" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_fcbe490dc37a1abf68f19c5ccb9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_lockdowns" ADD CONSTRAINT "FK_e2323be78c2e914aac38ffbbb1f" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_lockdowns" ADD CONSTRAINT "FK_d461037198c59a2018b43b7e331" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "federation_moderations" ADD CONSTRAINT "FK_420b12a7a37822e748276ae4a8f" FOREIGN KEY ("localUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "federation_moderations" ADD CONSTRAINT "FK_8d5c3c957770e934d6d09eb6194" FOREIGN KEY ("remoteUserId") REFERENCES "federated_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brainwave_devices" ADD CONSTRAINT "FK_722e06ff923767d8cc71efab558" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "biometric_devices" ADD CONSTRAINT "FK_14f54e10793f1e2ec41c8075e73" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "verification_history" ADD CONSTRAINT "FK_4e4ae4880fc623e5603fa046c4a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "verification_badges" ADD CONSTRAINT "FK_daf86c0c0e806c0d047443e6f84" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trust_indicators" ADD CONSTRAINT "FK_d1dd47df7dbad1fff04a54bf861" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "security_alerts" ADD CONSTRAINT "FK_2ecd034b682f561da0efdea87d9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "login_approvals" ADD CONSTRAINT "FK_45a3595df1ab19e16ba364956e3" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "linked_accounts" ADD CONSTRAINT "FK_2c77d2a0c06eeab6e62dc35af64" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity_settings" ADD CONSTRAINT "FK_065a1847df05510051ec6d81948" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_mutes" ADD CONSTRAINT "FK_cbedf76ebb0511716da7a6e9b14" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_mutes" ADD CONSTRAINT "FK_06f5a843540d98f44e7abbb47a5" FOREIGN KEY ("mutedUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_mutes" DROP CONSTRAINT "FK_06f5a843540d98f44e7abbb47a5"`);
        await queryRunner.query(`ALTER TABLE "user_mutes" DROP CONSTRAINT "FK_cbedf76ebb0511716da7a6e9b14"`);
        await queryRunner.query(`ALTER TABLE "identity_settings" DROP CONSTRAINT "FK_065a1847df05510051ec6d81948"`);
        await queryRunner.query(`ALTER TABLE "linked_accounts" DROP CONSTRAINT "FK_2c77d2a0c06eeab6e62dc35af64"`);
        await queryRunner.query(`ALTER TABLE "login_approvals" DROP CONSTRAINT "FK_45a3595df1ab19e16ba364956e3"`);
        await queryRunner.query(`ALTER TABLE "security_alerts" DROP CONSTRAINT "FK_2ecd034b682f561da0efdea87d9"`);
        await queryRunner.query(`ALTER TABLE "trust_indicators" DROP CONSTRAINT "FK_d1dd47df7dbad1fff04a54bf861"`);
        await queryRunner.query(`ALTER TABLE "verification_badges" DROP CONSTRAINT "FK_daf86c0c0e806c0d047443e6f84"`);
        await queryRunner.query(`ALTER TABLE "verification_history" DROP CONSTRAINT "FK_4e4ae4880fc623e5603fa046c4a"`);
        await queryRunner.query(`ALTER TABLE "biometric_devices" DROP CONSTRAINT "FK_14f54e10793f1e2ec41c8075e73"`);
        await queryRunner.query(`ALTER TABLE "brainwave_devices" DROP CONSTRAINT "FK_722e06ff923767d8cc71efab558"`);
        await queryRunner.query(`ALTER TABLE "federation_moderations" DROP CONSTRAINT "FK_8d5c3c957770e934d6d09eb6194"`);
        await queryRunner.query(`ALTER TABLE "federation_moderations" DROP CONSTRAINT "FK_420b12a7a37822e748276ae4a8f"`);
        await queryRunner.query(`ALTER TABLE "group_lockdowns" DROP CONSTRAINT "FK_d461037198c59a2018b43b7e331"`);
        await queryRunner.query(`ALTER TABLE "group_lockdowns" DROP CONSTRAINT "FK_e2323be78c2e914aac38ffbbb1f"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_fcbe490dc37a1abf68f19c5ccb9"`);
        await queryRunner.query(`ALTER TABLE "checkout_sessions" DROP CONSTRAINT "FK_6cd3a3b2162be33e3bd209a61a9"`);
        await queryRunner.query(`ALTER TABLE "checkout_sessions" DROP CONSTRAINT "FK_4f7d6d4e50548afac8d8abc4b47"`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" DROP CONSTRAINT "FK_821f590b8289b844d4c5790242d"`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" DROP CONSTRAINT "FK_98f900b8c9f8964a2639b24636b"`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" DROP CONSTRAINT "FK_17d30a05cc8f0ea38b111f87e42"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP CONSTRAINT "FK_842bd48e94f1d75a88221cfe35a"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP CONSTRAINT "FK_32edd80d91dff1bc19e79c8f16d"`);
        await queryRunner.query(`ALTER TABLE "oauth_authorizations" DROP CONSTRAINT "FK_5baf2013e4d6649133b7ef56e38"`);
        await queryRunner.query(`ALTER TABLE "oauth_authorizations" DROP CONSTRAINT "FK_1f2a4e59d61f895125d25bd3bc0"`);
        await queryRunner.query(`ALTER TABLE "oauth_apps" DROP CONSTRAINT "FK_e7b22a2aeff109168c16a89af28"`);
        await queryRunner.query(`ALTER TABLE "scheduled_posts" DROP CONSTRAINT "FK_83cbdfc52c73171cdff3b55e090"`);
        await queryRunner.query(`ALTER TABLE "security_audit_logs" DROP CONSTRAINT "FK_d7f3413ad98f1a72ef76e84bfec"`);
        await queryRunner.query(`ALTER TABLE "subscription_bundle_tiers" DROP CONSTRAINT "FK_abe75c2db50cdd3085b4b8a055b"`);
        await queryRunner.query(`ALTER TABLE "subscription_bundle_tiers" DROP CONSTRAINT "FK_5321aaecbd03592a0473f1e7eba"`);
        await queryRunner.query(`ALTER TABLE "subscription_bundles" DROP CONSTRAINT "FK_5186f53d7ad15cb9205d75a045e"`);
        await queryRunner.query(`ALTER TABLE "tax_documents" DROP CONSTRAINT "FK_d8ff960bc60b938ef2a27cc3407"`);
        await queryRunner.query(`ALTER TABLE "threads" DROP CONSTRAINT "FK_a6cc1a07ec07e376947ed1016a0"`);
        await queryRunner.query(`ALTER TABLE "thread_messages" DROP CONSTRAINT "FK_a82b034de86ec3aa77236c06cf8"`);
        await queryRunner.query(`ALTER TABLE "thread_messages" DROP CONSTRAINT "FK_8a4e138370619824c68b6e9a419"`);
        await queryRunner.query(`ALTER TABLE "thread_messages" DROP CONSTRAINT "FK_c6bc073e77f201aa2fdbaa1688e"`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" DROP CONSTRAINT "FK_c441120e2325a477c968c5caab2"`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" DROP CONSTRAINT "FK_8bd665642c690d77c06ef44c2fc"`);
        await queryRunner.query(`ALTER TABLE "webhook_deliveries" DROP CONSTRAINT "FK_9f63fc91ff6cbd3f8238b9a7812"`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" DROP CONSTRAINT "FK_6c70d1c965d029dcd2af34025db"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP CONSTRAINT "FK_f8f7551b0df6a9d20a328125305"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP CONSTRAINT "FK_5aeaa2dd850bc2ca311c793716d"`);
        await queryRunner.query(`ALTER TABLE "webhook_endpoints" DROP CONSTRAINT "FK_ad15290f0cf98302ad7d68eae1c"`);
        await queryRunner.query(`ALTER TABLE "articles" DROP CONSTRAINT "FK_65d9ccc1b02f4d904e90bd76a34"`);
        await queryRunner.query(`ALTER TABLE "course_enrollments" DROP CONSTRAINT "FK_ab72c7fa06784137e905f1f8b8e"`);
        await queryRunner.query(`ALTER TABLE "course_enrollments" DROP CONSTRAINT "FK_d77e489db35c7d325700d799be6"`);
        await queryRunner.query(`ALTER TABLE "course_lessons" DROP CONSTRAINT "FK_a4dc7855b148a230609fbf38542"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_fffcbc92f4e8fa650d08be6903d"`);
        await queryRunner.query(`ALTER TABLE "invite_codes" DROP CONSTRAINT "FK_7b103c31f0945f90b2af8d8ba0b"`);
        await queryRunner.query(`ALTER TABLE "one_time_prekeys" DROP CONSTRAINT "FK_d8ca4e460ce7e0199de5d2280cc"`);
        await queryRunner.query(`ALTER TABLE "prekey_bundles" DROP CONSTRAINT "FK_a65ce317a25ffadf33195a345df"`);
        await queryRunner.query(`ALTER TABLE "signed_prekeys" DROP CONSTRAINT "FK_a0673f4690e84acb219961c1f29"`);
        await queryRunner.query(`ALTER TABLE "newsletter_newslettersubscribers" DROP CONSTRAINT "FK_9627377ca0a655d80675ed0b467"`);
        await queryRunner.query(`ALTER TABLE "newsletter_newslettersubscribers" DROP CONSTRAINT "FK_c1ee4bbf7d7e34afd9ade85f3f9"`);
        await queryRunner.query(`ALTER TABLE "newsletter_subscribers" DROP CONSTRAINT "FK_52d6367f00d79849e585cf1e583"`);
        await queryRunner.query(`ALTER TABLE "newsletters" DROP CONSTRAINT "FK_35109ef4f622c1c4619bd30fc4c"`);
        await queryRunner.query(`ALTER TABLE "podcasts" DROP CONSTRAINT "FK_7512a5861f9118a14e1d1bc9cd2"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_dda1f23593417fecd7a0d65033e"`);
        await queryRunner.query(`ALTER TABLE "federation_moderations" DROP CONSTRAINT "UQ_db6a1ff672d21a5fe28f058693b"`);
        await queryRunner.query(`ALTER TABLE "tax_documents" DROP CONSTRAINT "UQ_tax_document_user_year_form"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06f5a843540d98f44e7abbb47a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cbedf76ebb0511716da7a6e9b1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37d14e3c45fb3cb5791a329468"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce84151068834d5bfd63476156"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d7629c18e0f5c46814bfe1ef9d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c54d74cdd7d268d6d6940d79a6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f99d7fc3faae6108e514e8f00f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_00c876f1efd81fe6c660ac20fd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0098a8274e33105c09719f8c5b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_503562c3b6df8516ae43a2f052"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b41c0c7dfa44b7228345042b93"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4bd2925abbcfa498a9bfcbc3af"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0187f2cd124ed7c9c4ff579744"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b227208d15421af07c85d5abfd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c3081b6c7215589e8a4e00335"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1ab3a29295d5c2507d606a1fb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f198f0b1b0f69f186634733df0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8e61e380f80a7426c17563d0a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d66463591cafc24369366a0122"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4007f95dc9b4b7d9c6aa5c813"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f60af098356f98fe6cfa060e3d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3358e0885c861821636fdaa25c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d5c3c957770e934d6d09eb619"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_420b12a7a37822e748276ae4a8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab52c6673c6c1f6d54b63e60a6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f2a4e59d61f895125d25bd3bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94005563c4ba7cabe1e59b937d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1ec1d0077a9029a4e4d3da930"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f63fc91ff6cbd3f8238b9a781"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6c70d1c965d029dcd2af34025d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1123ff6815c5b8fec0ba9fec37"`);
        await queryRunner.query(`ALTER TABLE "document_verification_stats" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "document_verification_appeals" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "document_verification_appeals" ALTER COLUMN "submittedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "document_verification_appeals" ALTER COLUMN "status" SET DEFAULT 'submitted'`);
        await queryRunner.query(`ALTER TABLE "document_verification_audit_logs" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "document_validation_rules" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "document_validation_rules" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "document_validation_rules" ALTER COLUMN "severity" SET DEFAULT 'warning'`);
        await queryRunner.query(`ALTER TABLE "document_verification_records" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "document_verification_records" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "document_verification_records" ALTER COLUMN "submittedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "document_verification_records" ALTER COLUMN "status" SET DEFAULT 'submitted'`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" DROP COLUMN "links"`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" ADD "links" jsonb NOT NULL DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" DROP COLUMN "documentUrls"`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" ADD "documentUrls" jsonb NOT NULL DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" ADD "requestId" uuid NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."verification_requests_status_enum_old" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ALTER COLUMN "status" TYPE "public"."verification_requests_status_enum_old" USING "status"::"text"::"public"."verification_requests_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."verification_requests_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."verification_requests_status_enum_old" RENAME TO "verification_requests_status_enum"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ALTER COLUMN "userId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "brainwave_devices" ALTER COLUMN "userId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" ADD "description" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "instance_keys" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "instance_keys" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "instance_keys" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "instance_keys" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "checkout_sessions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "checkout_sessions" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "checkout_sessions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "checkout_sessions" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "checkout_sessions" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."checkout_sessions_status_enum"`);
        await queryRunner.query(`ALTER TABLE "checkout_sessions" ADD "status" character varying NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."escrow_transactions_status_enum"`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" ADD "status" character varying NOT NULL DEFAULT 'held'`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP COLUMN "images"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD "images" character varying array`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD "title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scheduled_posts" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "scheduled_posts" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "threads" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "threads" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "threads" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "threads" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "thread_messages" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "thread_messages" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."verification_requests_status_enum_old" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ALTER COLUMN "status" TYPE "public"."verification_requests_status_enum_old" USING "status"::"text"::"public"."verification_requests_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."verification_requests_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."verification_requests_status_enum_old" RENAME TO "verification_requests_status_enum"`);
        await queryRunner.query(`ALTER TABLE "articles" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "articles" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "articles" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "articles" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "articles" DROP COLUMN "tags"`);
        await queryRunner.query(`ALTER TABLE "articles" ADD "tags" character varying array`);
        await queryRunner.query(`ALTER TABLE "articles" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."articles_status_enum"`);
        await queryRunner.query(`ALTER TABLE "articles" ADD "status" character varying NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "course_enrollments" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "course_enrollments" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "course_enrollments" DROP COLUMN "completedLessons"`);
        await queryRunner.query(`ALTER TABLE "course_enrollments" ADD "completedLessons" character varying array`);
        await queryRunner.query(`ALTER TABLE "course_lessons" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "course_lessons" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "course_lessons" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "course_lessons" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."courses_status_enum"`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "status" character varying NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "one_time_prekeys" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "one_time_prekeys" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "prekey_bundles" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "prekey_bundles" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "signed_prekeys" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "signed_prekeys" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "newsletter_newslettersubscribers" DROP COLUMN "subscribedAt"`);
        await queryRunner.query(`ALTER TABLE "newsletter_newslettersubscribers" ADD "subscribedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "newsletter_subscribers" DROP COLUMN "subscribedAt"`);
        await queryRunner.query(`ALTER TABLE "newsletter_subscribers" ADD "subscribedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "newsletters" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "newsletters" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "newsletters" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "newsletters" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "newsletters" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."newsletters_status_enum"`);
        await queryRunner.query(`ALTER TABLE "newsletters" ADD "status" character varying NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "podcasts" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "podcasts" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "podcasts" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "podcasts" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "podcasts" DROP COLUMN "tags"`);
        await queryRunner.query(`ALTER TABLE "podcasts" ADD "tags" character varying array`);
        await queryRunner.query(`ALTER TABLE "podcasts" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."podcasts_status_enum"`);
        await queryRunner.query(`ALTER TABLE "podcasts" ADD "status" character varying NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "nextAppealEligibleAt"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "appealCount"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "reviewedAt"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "submittedAt"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "reviewedBy"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "rejectionReason"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "documentUrl"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."verification_requests_type_enum"`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" DROP COLUMN "totalVotes"`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" DROP COLUMN "abstainVotes"`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" DROP COLUMN "noVotes"`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" DROP COLUMN "yesVotes"`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" DROP COLUMN "treasuryAmount"`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" DROP COLUMN "votingEndsAt"`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" DROP COLUMN "passThreshold"`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" DROP COLUMN "quorum"`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."dao_proposal_status_enum"`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."dao_proposal_type_enum"`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" DROP CONSTRAINT "UQ_9f8e1468d806ae7d98169bc78a3"`);
        await queryRunner.query(`ALTER TABLE "dao_proposal" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "reviewedById"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "reviewNote"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "links"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "justification"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "documentType"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "organizationName"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "verification_requests" DROP COLUMN "workflow"`);
        await queryRunner.query(`DROP TYPE "public"."verification_requests_workflow_enum"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isGuest"`);
        await queryRunner.query(`ALTER TABLE "nonprofits" DROP COLUMN "rejectionReason"`);
        await queryRunner.query(`ALTER TABLE "token_gated_content" DROP COLUMN "tier"`);
        await queryRunner.query(`ALTER TABLE "token_gated_content" DROP COLUMN "chainId"`);
        await queryRunner.query(`CREATE TYPE "public"."verification_requests_category_enum" AS ENUM('creator', 'business', 'journalist', 'government', 'nonprofit', 'other')`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "category" "public"."verification_requests_category_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "links" jsonb NOT NULL DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "justification" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "reviewedById" uuid`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD "reviewNote" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "deviceId" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "registrationId" integer`);
        await queryRunner.query(`DROP INDEX "public"."IDX_065a1847df05510051ec6d8194"`);
        await queryRunner.query(`DROP TABLE "identity_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ba6eb6c390ea493cd072735ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85a88f8035617f15d7d5749104"`);
        await queryRunner.query(`DROP TABLE "linked_accounts"`);
        await queryRunner.query(`DROP TYPE "public"."linked_accounts_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_454cadf17c215212f16993cd55"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a5d8198376a76b0d668dcf423"`);
        await queryRunner.query(`DROP TABLE "login_approvals"`);
        await queryRunner.query(`DROP TYPE "public"."login_approvals_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1dd47df7dbad1fff04a54bf86"`);
        await queryRunner.query(`DROP TABLE "trust_indicators"`);
        await queryRunner.query(`DROP TYPE "public"."trust_indicators_trustlevel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f17990a187f550345129925d5"`);
        await queryRunner.query(`DROP TABLE "verification_badges"`);
        await queryRunner.query(`DROP TYPE "public"."verification_badges_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_519bc2d63c2d3a5f9fe4f4a19b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94429d4ee17e28bf15bd918ef7"`);
        await queryRunner.query(`DROP TABLE "verification_history"`);
        await queryRunner.query(`DROP TYPE "public"."verification_history_eventtype_enum"`);
        await queryRunner.query(`DROP TABLE "biometric_devices"`);
        await queryRunner.query(`ALTER TABLE "federation_moderations" ADD CONSTRAINT "UQ_federation_moderations_pair" UNIQUE ("localUserId", "remoteUserId")`);
        await queryRunner.query(`CREATE INDEX "IDX_user_mutes_muted_user" ON "user_mutes" ("mutedUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_security_alerts_user_status_date" ON "security_alerts" ("createdAt", "resolved", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_stats_date" ON "document_verification_stats" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_appeals_createdAt" ON "document_verification_appeals" ("submittedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_appeals_status" ON "document_verification_appeals" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_appeals_documentRecordId" ON "document_verification_appeals" ("documentRecordId") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_logs_createdAt" ON "document_verification_audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_logs_action" ON "document_verification_audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_logs_accountId" ON "document_verification_audit_logs" ("accountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_rules_enabled" ON "document_validation_rules" ("enabled") `);
        await queryRunner.query(`CREATE INDEX "IDX_doc_records_accountId_status" ON "document_verification_records" ("accountId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_doc_records_submittedAt" ON "document_verification_records" ("submittedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_doc_records_documentId" ON "document_verification_records" ("documentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_doc_records_status" ON "document_verification_records" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_doc_records_accountId" ON "document_verification_records" ("accountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_brainwave_devices_userId" ON "brainwave_devices" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_connected_accounts_userId" ON "connected_accounts" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_custom_audiences_userId" ON "custom_audiences" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_federation_moderations_remote_user" ON "federation_moderations" ("remoteUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_federation_moderations_local_user" ON "federation_moderations" ("localUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_product_reviews_productId" ON "product_reviews" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_oauth_auth_app" ON "oauth_authorizations" ("appId") `);
        await queryRunner.query(`CREATE INDEX "IDX_oauth_auth_codeHash" ON "oauth_authorizations" ("codeHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_scheduled_posts_status_due" ON "scheduled_posts" ("scheduled_for", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_scheduled_posts_user_id" ON "scheduled_posts" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_tax_document_user_year_form" ON "tax_documents" ("formType", "taxYear", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_threads_user_id" ON "threads" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_thread_messages_user_id" ON "thread_messages" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_thread_messages_thread_id" ON "thread_messages" ("thread_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_tip_recipient_created" ON "tip" ("createdAt", "toId") `);
        await queryRunner.query(`CREATE INDEX "IDX_verification_appeals_user_submitted" ON "verification_appeals" ("submittedAt", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_verification_appeals_request_status" ON "verification_appeals" ("requestId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_webhook_deliveries_endpoint" ON "webhook_deliveries" ("endpointId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ledger_entries_userId" ON "ledger_entries" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_articles_publishedAt" ON "articles" ("publishedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_articles_authorId" ON "articles" ("authorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_articles_status" ON "articles" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_articles_slug" ON "articles" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_courses_slug" ON "courses" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_invite_codes_code" ON "invite_codes" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_otpk_userId_unused" ON "one_time_prekeys" ("isUsed", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_otpk_userId" ON "one_time_prekeys" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_pkb_userId" ON "prekey_bundles" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_spk_userId" ON "signed_prekeys" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_podcasts_status" ON "podcasts" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_podcasts_slug" ON "podcasts" ("slug") `);
        await queryRunner.query(`ALTER TABLE "user_mutes" ADD CONSTRAINT "FK_user_mutes_muted_user" FOREIGN KEY ("mutedUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_mutes" ADD CONSTRAINT "FK_user_mutes_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "security_alerts" ADD CONSTRAINT "FK_security_alerts_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD CONSTRAINT "FK_f8f7551b0df6a9d20a328125305" FOREIGN KEY ("reviewedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "verification_requests" ADD CONSTRAINT "FK_5aeaa2dd850bc2ca311c793716d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brainwave_devices" ADD CONSTRAINT "FK_brainwave_devices_userId" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "federation_moderations" ADD CONSTRAINT "FK_federation_moderations_remote_user" FOREIGN KEY ("remoteUserId") REFERENCES "federated_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "federation_moderations" ADD CONSTRAINT "FK_federation_moderations_local_user" FOREIGN KEY ("localUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_lockdowns" ADD CONSTRAINT "FK_group_lockdowns_creator" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_lockdowns" ADD CONSTRAINT "FK_group_lockdowns_group" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_invoices_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "checkout_sessions" ADD CONSTRAINT "FK_checkout_productId" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "checkout_sessions" ADD CONSTRAINT "FK_checkout_buyerId" FOREIGN KEY ("buyerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" ADD CONSTRAINT "FK_escrow_productId" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" ADD CONSTRAINT "FK_escrow_sellerId" FOREIGN KEY ("sellerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" ADD CONSTRAINT "FK_escrow_buyerId" FOREIGN KEY ("buyerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD CONSTRAINT "FK_product_reviews_reviewerId" FOREIGN KEY ("reviewerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD CONSTRAINT "FK_product_reviews_productId" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_authorizations" ADD CONSTRAINT "FK_oauth_auth_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_authorizations" ADD CONSTRAINT "FK_oauth_auth_app" FOREIGN KEY ("appId") REFERENCES "oauth_apps"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_apps" ADD CONSTRAINT "FK_oauth_apps_developer" FOREIGN KEY ("developerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduled_posts" ADD CONSTRAINT "FK_scheduled_posts_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "security_audit_logs" ADD CONSTRAINT "FK_security_audit_logs_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_bundle_tiers" ADD CONSTRAINT "FK_bundle_tiers_tier" FOREIGN KEY ("tierId") REFERENCES "subscription_tiers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_bundle_tiers" ADD CONSTRAINT "FK_bundle_tiers_bundle" FOREIGN KEY ("bundleId") REFERENCES "subscription_bundles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_bundles" ADD CONSTRAINT "FK_subscription_bundles_creator" FOREIGN KEY ("creatorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_documents" ADD CONSTRAINT "FK_tax_documents_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "threads" ADD CONSTRAINT "FK_threads_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "thread_messages" ADD CONSTRAINT "FK_thread_messages_parent_message_id" FOREIGN KEY ("parent_message_id") REFERENCES "thread_messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "thread_messages" ADD CONSTRAINT "FK_thread_messages_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "thread_messages" ADD CONSTRAINT "FK_thread_messages_thread_id" FOREIGN KEY ("thread_id") REFERENCES "threads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" ADD CONSTRAINT "FK_verification_appeals_request" FOREIGN KEY ("requestId") REFERENCES "verification_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "verification_appeals" ADD CONSTRAINT "FK_verification_appeals_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webhook_deliveries" ADD CONSTRAINT "FK_webhook_deliveries_endpoint" FOREIGN KEY ("endpointId") REFERENCES "webhook_endpoints"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" ADD CONSTRAINT "FK_ledger_entries_userId" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webhook_endpoints" ADD CONSTRAINT "FK_webhook_endpoints_developer" FOREIGN KEY ("developerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "articles" ADD CONSTRAINT "FK_articles_authorId" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_enrollments" ADD CONSTRAINT "FK_course_enrollments_userId" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_enrollments" ADD CONSTRAINT "FK_course_enrollments_courseId" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_lessons" ADD CONSTRAINT "FK_course_lessons_courseId" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_courses_authorId" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invite_codes" ADD CONSTRAINT "FK_invite_codes_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "one_time_prekeys" ADD CONSTRAINT "FK_otpk_userId" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prekey_bundles" ADD CONSTRAINT "FK_pkb_userId" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signed_prekeys" ADD CONSTRAINT "FK_spk_userId" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "newsletter_newslettersubscribers" ADD CONSTRAINT "FK_nns_subscriberId" FOREIGN KEY ("subscriberId") REFERENCES "newsletter_subscribers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "newsletter_newslettersubscribers" ADD CONSTRAINT "FK_nns_authorId" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "newsletter_subscribers" ADD CONSTRAINT "FK_newsletter_subscribers_userId" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "newsletters" ADD CONSTRAINT "FK_newsletters_authorId" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "podcasts" ADD CONSTRAINT "FK_podcasts_authorId" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_posts_quotedPost" FOREIGN KEY ("quotedPostId") REFERENCES "posts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
