import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  ManyToOne,
} from 'typeorm';
import { Post } from '../../posts/entities/post.entity';

export enum VideoResolution {
  RES_720P = '720p',
  RES_1080P = '1080p',
  RES_4K = '4k',
  RES_8K = '8k',
}

export interface VideoTrack {
  id: string;
  type: 'video' | 'audio' | 'subtitle';
  url: string;
  name: string;
  startTime: number;
  endTime: number;
  enabled: boolean;
}

@Entity('media')
export class Media {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ type: 'varchar', length: 2048 })
  url: string;

  @Column({ type: 'varchar', length: 20 })
  type: 'image' | 'video' | 'audio';

  @Column({ type: 'int', default: 0 })
  sortOrder: number;

  @Column({ type: 'text', nullable: true })
  altText: string;

  @Column({ type: 'varchar', length: 2048, nullable: true })
  captionsUrl: string;

  @Column({
    type: 'enum',
    enum: VideoResolution,
    nullable: true,
  })
  resolution?: VideoResolution;

  @Column({ type: 'jsonb', nullable: true })
  tracks?: VideoTrack[];

  @Column({ type: 'boolean', default: false })
  autoGeneratedCaptions: boolean;

  @ManyToOne(() => Post, (post) => post.media)
  post: Post;
}