import { IsString, IsNotEmpty, IsUUID, IsOptional, IsEnum, IsBoolean, IsArray, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';
import { PostVisibility } from '../../posts/entities/post.entity';
import { VideoResolution } from '../../media/entities/media.entity';

class VideoTrackDto {
  @IsString()
  @IsNotEmpty()
  id: string;

  @IsString()
  @IsNotEmpty()
  type: 'video' | 'audio' | 'subtitle';

  @IsString()
  @IsNotEmpty()
  url: string;

  @IsString()
  @IsNotEmpty()
  name: string;

  @IsNotEmpty()
  startTime: number;

  @IsNotEmpty()
  endTime: number;

  @IsBoolean()
  enabled: boolean;
}

export class CreateReelDto {
  @IsString()
  @IsNotEmpty()
  content?: string;

  @IsUUID()
  @IsNotEmpty()
  mediaId: string;

  @IsUUID()
  @IsOptional()
  effectId?: string;

  @IsEnum(PostVisibility)
  @IsOptional()
  visibility?: PostVisibility = PostVisibility.PUBLIC;

  @IsString()
  @IsOptional()
  locationName?: string;

  @IsEnum(VideoResolution)
  @IsOptional()
  resolution?: VideoResolution;

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => VideoTrackDto)
  @IsOptional()
  tracks?: VideoTrackDto[];

  @IsBoolean()
  @IsOptional()
  autoGeneratedCaptions?: boolean;
}