const test = require('node:test');
const assert = require('node:assert/strict');
const { analyzeNeuralAuthenticity } = require('../src/memories/deepfake-detection');

test('detects authentic personal memory cues', () => {
  const result = analyzeNeuralAuthenticity({
    content: 'I still remember the rain on the train window during our trip to Lisbon, the smell of coffee, and how my hands felt cold when I held your sleeve.',
    memoryMetadata: {
      emotions: { joy: 20, sadness: 10, excitement: 15, calm: 0, anger: 0, surprise: 10, love: 25, fear: 5 },
      context: { location: { name: 'Lisbon train station' } },
      sensory: { visual: [{ url: 'https://example.com/photo.jpg', type: 'image' }], audio: [{ url: 'https://example.com/audio.mp3', type: 'audio' }] },
    },
  });

  assert.equal(result.verdict, 'likely_authentic');
  assert.ok(result.score >= 0.65);
  assert.ok(result.signals.includes('sensory media present'));
});

test('flags generic AI-style phrases as synthetic', () => {
  const result = analyzeNeuralAuthenticity({
    content: 'A stunningly perfect cinematic scene generated by a prompt that vividly captures beauty and harmony.',
    memoryMetadata: {},
  });

  assert.equal(result.verdict, 'likely_synthetic');
  assert.ok(result.score < 0.5);
  assert.ok(result.signals.some((signal) => signal.includes('synthetic')));
});
