import { Injectable, NotFoundException, UnauthorizedException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, Not } from 'typeorm';
import { ReelEffect } from './entities/reel-effect.entity';
import { Post, PostType, PostVisibility } from '../posts/entities/post.entity';
import { User } from '../users/entities/user.entity';
import { CreateReelDto } from './dto/create-reel.dto';
import { UpdateReelDto } from './dto/update-reel.dto';
import { CreateReelEffectDto } from './dto/create-reel-effect.dto';
import { Media } from '../media/entities/media.entity';

@Injectable()
export class ReelsService {
  constructor(
    @InjectRepository(ReelEffect)
    private readonly reelEffectRepository: Repository<ReelEffect>,
    @InjectRepository(Post)
    private readonly postRepository: Repository<Post>,
    @InjectRepository(Media)
    private readonly mediaRepository: Repository<Media>,
  ) {}

  async getReelById(id: string): Promise<Post> {
    const post = await this.postRepository.findOne({
      where: { id },
      relations: ['user', 'comments', 'comments.user', 'reactions', 'reelEffect'],
    });
    if (!post) {
      throw new Error('Reel not found');
    }
    return post;
  }

  async getReelSuggestions(user: User): Promise<Post[]> {
    // Get all posts that are reels (have reelEffect) and are public
    const posts = await this.postRepository.find({
      relations: ['user', 'comments', 'comments.user', 'reactions', 'reelEffect'],
      where: {
        reelEffect: { id: Not(null) }, // Only return posts that are reels (have a reel effect applied)
        visibility: PostVisibility.PUBLIC,
      },
      order: {
        viewCount: 'DESC', // Sort by most viewed first
        createdAt: 'DESC',
      },
    });

    // Filter out the user's own posts
    const otherUsersPosts = posts.filter(post => post.user.id !== user.id);
    
    // Calculate engagement score for each post (views + likes*2 + comments*3 + shares*5) to prioritize popular content
    const postsWithEngagement = otherUsersPosts.map(post => {
      const likeCount = post.reactions.length;
      const commentCount = post.comments.length;
      const shareCount = post.shareCount || 0;
      const engagementScore = post.viewCount + (likeCount * 2) + (commentCount * 3) + (shareCount * 5);
      return { ...post, engagementScore };
    });

    // Sort by engagement score to show most engaging content first
    return postsWithEngagement.sort((a, b) => b.engagementScore - a.engagementScore);
  }

  async getReelEffects(): Promise<ReelEffect[]> {
    return this.reelEffectRepository.find();
  }

  async shareReel(id: string): Promise<void> {
    await this.postRepository.increment({ id }, 'shareCount', 1);
  }

  async trackView(id: string): Promise<void> {
    await this.postRepository.increment({ id }, 'viewCount', 1);
  }

  async getReelInsights(id: string, user: User): Promise<any> {
    const post = await this.postRepository.findOne({ where: { id }, relations: ['user', 'reactions', 'comments'] });

    if (!post || post.user.id !== user.id) {
      throw new NotFoundException('Post not found or user not authorized');
    }

    return {
      viewCount: post.viewCount,
      likeCount: post.reactions.length,
      commentCount: post.comments.length,
      shareCount: post.shareCount,
    };
  }

  async createReel(createReelDto: CreateReelDto, user: User): Promise<Post> {
    const media = await this.mediaRepository.findOne({ where: { id: createReelDto.mediaId } });
    if (!media) {
      throw new NotFoundException('Media not found');
    }

    // Update media with advanced video editing metadata
    if (createReelDto.resolution) {
      media.resolution = createReelDto.resolution;
    }
    if (createReelDto.tracks) {
      media.tracks = createReelDto.tracks;
    }
    if (createReelDto.autoGeneratedCaptions !== undefined) {
      media.autoGeneratedCaptions = createReelDto.autoGeneratedCaptions;
    }
    await this.mediaRepository.save(media);

    let reelEffect: ReelEffect | null = null;
    if (createReelDto.effectId) {
      reelEffect = await this.reelEffectRepository.findOne({ where: { id: createReelDto.effectId } });
      if (!reelEffect) {
        throw new NotFoundException('Reel effect not found');
      }
    }

    const reel = this.postRepository.create({
      ...createReelDto,
      postType: PostType.REEL,
      user,
      media: [media],
      reelEffect,
      viewCount: 0,
      shareCount: 0,
    });

    return this.postRepository.save(reel);
  }

  async updateReel(id: string, updateReelDto: UpdateReelDto, user: User): Promise<Post> {
    const reel = await this.postRepository.findOne({ 
      where: { id, postType: PostType.REEL },
      relations: ['user', 'reelEffect', 'media']
    });

    if (!reel) {
      throw new NotFoundException('Reel not found');
    }

    if (reel.user.id !== user.id) {
      throw new UnauthorizedException('You are not authorized to update this reel');
    }

    if (updateReelDto.effectId) {
      const reelEffect = await this.reelEffectRepository.findOne({ where: { id: updateReelDto.effectId } });
      if (!reelEffect) {
        throw new NotFoundException('Reel effect not found');
      }
      reel.reelEffect = reelEffect;
    }

    Object.assign(reel, updateReelDto);
    return this.postRepository.save(reel);
  }

  async deleteReel(id: string, user: User): Promise<void> {
    const reel = await this.postRepository.findOne({ 
      where: { id, postType: PostType.REEL },
      relations: ['user']
    });

    if (!reel) {
      throw new NotFoundException('Reel not found');
    }

    if (reel.user.id !== user.id) {
      throw new UnauthorizedException('You are not authorized to delete this reel');
    }

    await this.postRepository.remove(reel);
  }

  async getUserReels(userId: string): Promise<Post[]> {
    return this.postRepository.find({
      where: { 
        user: { id: userId },
        postType: PostType.REEL,
        visibility: Not(PostVisibility.PRIVATE)
      },
      relations: ['user', 'comments', 'comments.user', 'reactions', 'reelEffect', 'media'],
      order: { createdAt: 'DESC' },
    });
  }

  async createReelEffect(createReelEffectDto: CreateReelEffectDto): Promise<ReelEffect> {
    const effect = this.reelEffectRepository.create(createReelEffectDto);
    return this.reelEffectRepository.save(effect);
  }

  async updateReelEffect(id: string, updateReelEffectDto: Partial<CreateReelEffectDto>): Promise<ReelEffect> {
    const effect = await this.reelEffectRepository.findOne({ where: { id } });
    if (!effect) {
      throw new NotFoundException('Reel effect not found');
    }

    Object.assign(effect, updateReelEffectDto);
    return this.reelEffectRepository.save(effect);
  }

  async deleteReelEffect(id: string): Promise<void> {
    const result = await this.reelEffectRepository.delete(id);
    if (result.affected === 0) {
      throw new NotFoundException('Reel effect not found');
    }
  }
}